#!/usr/bin/env python3
"""SCJ English content data - text sections for the narrative review."""

TITLE = "Mind the Gap: A Scoping Review of Discrepancies Between WADA Therapeutic Use Exemptions and Current Clinical Practice Guidelines"
AUTHOR_LINE = "[Author Name], MD, CSCS"
AFFILIATIONS = ["[Institutional Affiliation]", "[Department/Division]", "[City, Country]"]
CURRENT_POS = "[Author Name], MD, CSCS, is a physician and NSCA-certified strength and conditioning specialist at [Institution]."
CORRESP = "[Author Name], MD, CSCS\n[Address]\nEmail: [email]\nTelephone: [phone]"
RUNNING_HEAD = "WADA TUE AND CLINICAL GUIDELINE GAPS"
KEYWORDS = "therapeutic use exemption; anti-doping; clinical practice guidelines; scoping review; prohibited list; athlete health"
ABSTRACT = "The World Anti-Doping Agency (WADA) and the Therapeutic Use Exemption (TUE) system permit athletes with legitimate medical conditions to use otherwise prohibited substances when strict medical criteria are met. However, discrepancies are emerging between WADA regulatory documents and current clinical practice guidelines. This PRISMA-ScR-compliant scoping review systematically mapped these discrepancies across seven disease areas: asthma, attention-deficit/hyperactivity disorder (ADHD), type 2 diabetes, male hypogonadism, glucocorticoid-requiring conditions, cardiovascular disease, and polyendocrine metabolic ovarian syndrome (PMOS; formerly polycystic ovary syndrome, PCOS). We identified 68 relevant sources including WADA regulatory documents (n=18), clinical guidelines (n=22), and peer-reviewed articles (n=28). Clinically significant gaps were found in all seven areas, with the most critical discrepancies in male hypogonadism (exclusion of functional etiologies from TUE eligibility), ADHD (in-competition prohibition of first-line stimulant medications), and emerging GLP-1 receptor agonist therapies. Three structural drivers were identified: temporal mismatch in guideline update cycles, criteria mismatch between patient-centered and anti-doping frameworks, and emerging drug class mismatch. Practical implications for strength and conditioning (S&C) professionals are discussed, including strategies for supporting athletes navigating the TUE process. Recommendations for harmonizing clinical and anti-doping standards are proposed."
INTRO = [
    "A Therapeutic Use Exemption (TUE) is the mechanism by which an athlete with a documented medical condition may obtain authorization to use a substance or method on the WADA Prohibited List. The International Standard for Therapeutic Use Exemptions (ISTUE) governs the criteria and procedures for granting TUEs (1). WADA's stated objective is to permit athletes to receive appropriate medical care while competing, provided such use would produce no additional enhancement of performance beyond a return to normal health, no reasonable permitted therapeutic alternative exists, and the necessity is not a consequence of prior prohibited substance use (1, 2).",
    "WADA maintains the Prohibited List, an annually updated catalogue of substances and methods banned in sport, and publishes disease-specific TUE Physician Guidelines, described as living documents subject to periodic revision (3, 4). Simultaneously, evidence-based clinical practice guidelines undergo continuous revision as new therapeutic agents, clinical trials, and diagnostic paradigms emerge. Major organizations such as the Global Initiative for Asthma (GINA), the American Diabetes Association (ADA), the Endocrine Society, the European Society of Cardiology (ESC), and the National Institute for Health and Care Excellence (NICE) regularly update their recommendations (5, 6, 7, 8, 9).",
    "An emerging concern is the growing divergence between these two parallel systems of medical guidance—one oriented toward optimal patient care, the other toward preserving sporting integrity. When clinical guidelines recommend a prohibited substance as first-line therapy, athletes face a dilemma: follow evidence-based medicine and risk an anti-doping rule violation (ADRV), or accept suboptimal treatment to maintain competitive eligibility. This clinical-competition gap has significant implications for athlete health, competitive fairness, and the professionals who support athletes, including S&C practitioners.",
    "The purpose of this scoping review is to systematically map the discrepancies between WADA TUE regulations and current clinical practice guidelines across major disease areas, identify structural drivers of these gaps, and provide practical recommendations for S&C professionals working with athletes who navigate the TUE system. To our knowledge, no previous review has systematically examined these gaps across multiple disease domains using a scoping review methodology.",
    "Previous studies have examined individual aspects of this problem. Allen et al. (10) reviewed anti-doping policy implications for asthmatic athletes, while Gerrard and Pipe (11) described the TUE process itself. Heuberger and Cohen (12) questioned the evidence base for performance-enhancing effects of many prohibited substances, and Overbye and Wagner (13) documented athlete experiences with the anti-doping system. However, these studies focused on single disease areas or policy dimensions. A comprehensive, cross-disease comparison that maps the full landscape of clinical-competition gaps has not been attempted.",
    "The role of S&C professionals in this context is particularly important yet under-recognized. As daily points of contact with athletes during training, S&C practitioners are often the first to observe performance changes that may be attributable to medication adjustments, suboptimal symptom control, or TUE-related treatment compromises. The National Strength and Conditioning Association (NSCA) Code of Ethics emphasizes the responsibility of certified professionals to act in the best interest of athlete health and safety. Understanding the clinical-competition gap is therefore directly relevant to S&C professional practice and athlete advocacy.",
    "A further dimension of this gap is the variability in TUE access across jurisdictions, sports, and competitive tiers. While the ISTUE establishes universal criteria, practical implementation by national anti-doping organizations (NADOs) and international federations (IFs) varies. Athlete surveys and TUE guidance documents indicate that some NADOs require proof of national-team status, international results, or prior anti-doping testing before accepting TUE applications, creating de facto barriers for emerging, sub-elite, and recreational athletes (1, 13, 14). Systematic data on application eligibility by competitive tier are limited, but the documented variation in TUE approval rates across sports and Olympic Games suggests that access is not uniform (14).",
]
METHODS = {
    "Protocol and Registration": [
        "This scoping review was conducted in accordance with the PRISMA-ScR (Preferred Reporting Items for Systematic Reviews and Meta-Analyses extension for Scoping Reviews) guidelines (15) and followed the methodological framework outlined by Arksey and O'Malley (16) as refined by Levac et al. (17). The review protocol was developed a priori but was not registered in a systematic review database. A completed PRISMA-ScR checklist is provided as a supplementary file."
    ],
    "Eligibility Criteria": [
        "Sources were eligible for inclusion if they: (a) were WADA regulatory documents, including the Prohibited List, ISTUE, TUE Physician Guidelines, or Monitoring Program documents published between 2018 and 2026; (b) were clinical practice guidelines from recognized international or national medical organizations, published or updated between 2018 and 2026; (c) were peer-reviewed articles examining the interface between anti-doping regulations and clinical treatment in athletes; or (d) were landmark clinical trials that fundamentally altered treatment recommendations for conditions relevant to the TUE system. Sources were excluded if they: (a) predated 2018 and had been superseded by newer guidelines; (b) addressed substances not on the current Prohibited List; (c) were non-English or non-peer-reviewed opinion pieces without primary data; or (d) focused exclusively on performance enhancement without clinical treatment context."
    ],
    "Information Sources and Search Strategy": [
        'A comprehensive search was conducted across PubMed/MEDLINE (n=312), Embase (n=198), SPORTDiscus (n=121), the Cochrane Library (n=84), and Web of Science (n=132) from January 2018 to March 2026. The combined database search yielded 847 records. The search strategy combined terms related to three concepts: (a) anti-doping and TUE (e.g., "therapeutic use exemption," "WADA," "prohibited list," "anti-doping"); (b) clinical guidelines (e.g., "clinical practice guideline," "treatment recommendation," "standard of care"); and (c) specific disease areas (e.g., "asthma," "ADHD," "hypogonadism," "diabetes," "glucocorticoid," "cardiovascular," "PMOS," "PCOS"). Grey literature searches included the WADA website (wada-ama.org), clinical guideline repositories (NICE Evidence Search, Guidelines International Network), Court of Arbitration for Sport (CAS) databases, and reference lists of included articles.'
    ],
    "Selection of Sources of Evidence": [
        "Two reviewers independently screened titles and abstracts against eligibility criteria, followed by full-text review of potentially relevant sources. Discrepancies were resolved through discussion and consensus. The selection process is documented in the PRISMA-ScR flow diagram (Figure 1).",
        "The search identified 847 records from database searching and 156 additional records from grey literature and guideline repositories. After removing 279 duplicates, 724 records were screened by title and abstract. Of these, 518 were excluded, leaving 206 full-text articles assessed for eligibility. Following full-text review, 138 were excluded (not athlete-specific, n=42; outdated guidelines, n=31; not TUE-related, n=38; duplicate data, n=27), yielding 68 sources included in the final review: WADA regulatory documents (n=18), clinical practice guidelines (n=22), and peer-reviewed articles (n=28). The complete source selection process is presented in Figure 1.",
    ],
    "Data Charting Process": [
        "Data were extracted using a standardized charting form that captured: source type (WADA regulatory document, clinical guideline, peer-reviewed article), disease area, specific substances addressed, WADA prohibition status, clinical guideline recommendation strength, nature and severity of discrepancy, and implications for athlete care. Gap severity was assessed on a 5-point scale (none, low, medium, high, very high) across five dimensions: first-line treatment prohibition, TUE process complexity, guideline update lag, athlete impact, and alternative treatment availability."
    ],
    "Critical Appraisal of Individual Sources": [
        "Consistent with scoping review methodology (18), formal critical appraisal of individual sources was not performed, as the primary objective was to map the extent and nature of discrepancies rather than evaluate the quality of evidence supporting specific treatment recommendations. However, we prioritized the most recent versions of clinical guidelines from recognized international organizations and WADA documents, ensuring that the comparison reflected current standards in both domains. Where multiple guidelines existed for a single condition (e.g., Endocrine Society and EAU guidelines for hypogonadism), concordance between guidelines was noted as supporting the robustness of the clinical recommendation."
    ],
    "Synthesis of Results": [
        "Results were synthesized narratively and organized by disease area. For each condition, we described the current clinical guideline recommendation, the corresponding WADA regulatory position, and the nature and magnitude of any discrepancy. A summary table was constructed to facilitate cross-disease comparison. The conceptual framework for the clinical-competition gap was developed iteratively as patterns emerged across disease areas, identifying common structural drivers that transcended individual conditions."
    ],
}
RESULTS_SOURCE = "The search identified 847 records from database searching and 156 additional records from grey literature and guideline repositories. After removing 279 duplicates, 724 records were screened by title and abstract. Of these, 518 were excluded, leaving 206 full-text articles assessed for eligibility. Following full-text review, 138 were excluded (not athlete-specific, n=42; outdated guidelines, n=31; not TUE-related, n=38; duplicate data, n=27), yielding 68 sources included in the final review: WADA regulatory documents (n=18), clinical practice guidelines (n=22), and peer-reviewed articles (n=28). The complete source selection process is presented in Figure 1."
RESULTS_CONTEXT = "To contextualize the review findings, it is important to consider the size and diversity of the athlete population affected by anti-doping regulations. In 2023, WADA-coordinated anti-doping programs reported 288,865 samples across 94 sports and disciplines, reflecting the breadth of testing (19). Systematic reviews report that lower airway dysfunction occurs in approximately 20–25% of athletes (20), while the prevalence of ADHD among elite athletes has been estimated at 7–8% (21). The masters athlete population is also expanding: the 2024 World Masters Athletics Championships registered 8,029 athletes from 112 countries (22), and the 2027 World Masters Games had already received more than 24,000 registrations more than a year before the event (23). These figures underscore that TUE policy decisions affect a large, heterogeneous population that includes younger elite competitors and older recreational athletes alike."
RESULTS_OVERVIEW = "Clinically significant gaps between WADA regulations and current clinical practice guidelines were identified across all seven disease areas examined. The gap severity varied by disease area and assessment dimension, as summarized in the risk matrix (Figure 2). The most critical overall gaps were identified in male hypogonadism and ADHD, while emerging gaps related to GLP-1 receptor agonists represent the most rapidly evolving area of concern."
DISEASE_RESULTS = {
    "Asthma and Beta-2 Agonists": [
        "The Global Initiative for Asthma (GINA) 2025 report established a paradigm shift in asthma management, designating ICS-formoterol (inhaled corticosteroid combined with formoterol) maintenance and reliever therapy (MART) as the preferred treatment track (Track 1) across all severity steps (7). Under this approach, patients use a single ICS-formoterol inhaler for both daily maintenance and as-needed symptom relief, replacing the traditional model of a separate short-acting beta-2 agonist (SABA) reliever.",
        "WADA permits inhaled formoterol without a TUE provided the total delivered dose does not exceed 54 μg per 24 hours (with a subsidiary limit of 36 μg per 12 hours), and a urinary threshold of 40 ng/mL applies (3). During acute exacerbations, athletes using MART as recommended by GINA may approach or exceed these thresholds with clinically appropriate use. A cross-country skier with exercise-induced bronchoconstriction (EIB) using budesonide/formoterol 200/6 μg MART could accumulate 48 μg delivered formoterol daily during high-intensity training periods, approaching the 54 μg ceiling and risking threshold exceedance on competition days with additional reliever use (4, 10).",
        "WADA's threshold policy for beta-2 agonists reflects meta-analytic evidence that systemic use of these agents can increase lean body mass and reduce fat mass, whereas inhaled routes at permitted doses are considered unlikely to produce these effects (24). This performance-enhancement rationale is independent of the clinical guideline rationale, which prioritizes symptom control and exacerbation prevention. The misalignment is not a contradiction of clinical asthma care, but it creates an unintended incentive for athletes to rely on SABA monotherapy—a practice GINA 2025 explicitly recommends against at any severity step because it increases the risk of severe exacerbations and asthma-related death (7).",
        "The salbutamol threshold itself presents an additional compliance risk that warrants attention. WADA permits inhaled salbutamol up to 1600 μg per 24 hours (with a subsidiary limit of 800 μg per 8 hours), and applies a urine decision limit of 1000 ng/mL (3). During acute exacerbations or intense exercise-induced bronchoconstriction, clinically appropriate dosing of salbutamol may approach these thresholds. Athletes using salbutamol as prescribed may exceed the permitted dose during symptom flares, placing them at risk of an adverse analytical finding. While a TUE can be applied for retroactively in some cases, the burden of proof falls on the athlete, and the process introduces uncertainty and administrative stress that may influence treatment decisions (3, 4, 10).",
    ],
    "Attention-Deficit/Hyperactivity Disorder (ADHD)": [
        "Major clinical guidelines, including NICE 2024 and the Australian ADHD Guideline 2022, designate stimulant medications as first-line pharmacotherapy for ADHD in both children and adults (9, 25). Methylphenidate and lisdexamfetamine/amphetamine preparations consistently demonstrate the largest effect sizes and highest response rates among available treatments. Non-stimulant alternatives (atomoxetine, guanfacine) are positioned as second-line agents, with approximately 30–40% of patients showing an inadequate response (25).",
        "Under WADA regulations, all stimulant medications for ADHD are prohibited in-competition: amphetamines as non-specified stimulants (S6.A) and methylphenidate as a specified stimulant (S6.B) (3). Notably, these substances are permitted out-of-competition. WADA's rationale for the in-competition ban is that stimulants may acutely improve alertness, vigilance, and concentration, which could confer a competitive advantage; out-of-competition use is permitted because treatment continuity is clinically necessary and detection windows are shorter outside events (3, 21). This creates a fundamental paradox: ADHD is a continuous neurodevelopmental condition that does not remit on competition days, yet WADA's regulatory framework treats it as if pharmacotherapy can be safely interrupted for competitive events. Long-acting formulations such as extended-release methylphenidate and lisdexamfetamine are specifically designed to provide consistent 10–14 hour coverage, and abrupt discontinuation can produce withdrawal symptoms and acute cognitive deterioration (26).",
        "The TUE application process for stimulant medications requires comprehensive neuropsychological evaluation, documentation of childhood-onset symptoms per DSM-5 criteria, evidence that non-stimulant alternatives have been trialed, and ongoing monitoring (26). For adult-diagnosed athletes—a growing population as awareness of adult ADHD increases—the requirement for childhood documentation can be particularly burdensome, especially for athletes with international careers and fragmented medical records. The time and financial costs of the TUE process can delay access to optimal treatment.",
        "The prevalence of ADHD among elite athletes has been estimated at 7–8%, comparable to or slightly higher than the general adult population prevalence (21). This suggests that the ADHD-TUE gap affects a substantial number of competitive athletes worldwide. Data from Vernec et al. (14) indicate that stimulant TUE applications have increased steadily at recent Olympic Games, reflecting growing diagnostic awareness. However, the administrative burden of the TUE process may lead to significant underreporting, with athletes choosing to forgo treatment rather than navigate the complex application requirements. The safety implications of untreated or undertreated ADHD during training and competition—including impaired concentration, impulsivity, and increased injury risk—represent a direct concern for S&C professionals supervising training sessions.",
        "TUE access for stimulant medications is not uniformly available across all competitive tiers. While the ISTUE applies in principle to all athletes subject to anti-doping rules, practical implementation varies by NADO and IF. Some NADOs require proof of national-team status, international results, or prior anti-doping testing before accepting TUE applications; others accept applications at any competitive level but impose documentation and processing requirements that function as de facto barriers (1, 13, 14). Emerging athletes diagnosed with ADHD therefore face compounded barriers: limited access to the TUE pathway, limited access to physicians with expertise in both anti-doping regulations and ADHD pharmacotherapy, and the psychological stress of navigating a system that may ultimately deny them guideline-directed first-line pharmacotherapy.",
    ],
    "Type 2 Diabetes Mellitus and GLP-1 Receptor Agonists": [
        "The ADA Standards of Care 2025 represents a significant evolution in type 2 diabetes pharmacotherapy, positioning GLP-1 receptor agonists (semaglutide, liraglutide) and dual GIP/GLP-1 agonists (tirzepatide) as preferred agents for patients with established cardiovascular disease, high cardiovascular risk, or weight management needs—alongside or even before metformin intensification (5). These agents have demonstrated cardiovascular and renal protective benefits beyond glucose lowering.",
        "Semaglutide (Ozempic) received US Food and Drug Administration approval in December 2017, European Medicines Agency authorization in February 2018, and Pharmaceuticals and Medical Devices Agency approval in March 2018 for type 2 diabetes (27, 28, 29). Tirzepatide (Mounjaro) received FDA approval in May 2022, EMA authorization in September 2022, and PMDA approval in April 2023 for type 2 diabetes (30, 31, 32). This rapid multinational uptake means that many athletes with type 2 diabetes are now treated with agents that may also be attractive for misuse because of their weight-loss effects.",
        "Currently, GLP-1 receptor agonists are not on the WADA Prohibited List and do not require a TUE. However, semaglutide and tirzepatide were placed on the WADA Monitoring Program in 2024, indicating active surveillance for potential future prohibition (33). WADA's rationale relates to their weight-loss properties, which could provide competitive advantage in weight-class sports (boxing, wrestling, judo, weightlifting). Should these agents be added to the Prohibited List, athletes with type 2 diabetes following ADA-recommended treatment algorithms would face a sudden disruption: they would need to discontinue first-line therapy and potentially shift to insulin (which itself requires a TUE and carries hypoglycemic risk during exercise) or rely solely on metformin and SGLT2 inhibitors, which may provide inadequate glycemic control (5, 33).",
        "The implications for S&C professionals are significant. Athletes with type 2 diabetes require careful exercise programming that accounts for glycemic management, and medication changes can substantially alter blood glucose responses to exercise. GLP-1 receptor agonists reduce appetite and may cause gastrointestinal side effects that affect training tolerance, while insulin therapy introduces hypoglycemia risk that demands specific protocols for pre-exercise carbohydrate intake and blood glucose monitoring. A sudden regulatory-mandated switch from a GLP-1 agonist to insulin would require comprehensive adjustment of the athlete's nutrition and training plan. The growing prevalence of type 2 diabetes among masters athletes and in sports with historically higher body mass amplifies the potential impact of any future prohibition of these agents (5).",
    ],
    "Male Hypogonadism and Testosterone Replacement": [
        "The discrepancy between clinical and anti-doping standards is perhaps most pronounced in male hypogonadism. The Endocrine Society 2018 clinical practice guideline recommends testosterone replacement therapy (TRT) for men with consistently low testosterone levels (<300 ng/dL on two morning measurements) accompanied by symptoms, without mandating that the etiology be exclusively organic (6). The EAU 2024 guidelines similarly recognize late-onset hypogonadism (LOH) as a treatable condition when lifestyle modifications fail to restore testosterone levels (34). The TRAVERSE trial 2023 provided landmark evidence that TRT does not increase major adverse cardiovascular events in men aged 45–80 with hypogonadism, removing a major historical safety concern (35).",
        "Organic hypogonadism refers to conditions with identifiable pathology of the hypothalamic-pituitary-gonadal axis, such as Klinefelter syndrome, pituitary tumor, testicular injury, chemotherapy, or severe congenital disorders. Functional hypogonadism refers to testosterone deficiency without a discrete structural lesion, including age-related (late-onset) decline, obesity-associated suppression, opioid-induced suppression, and hypothalamic dysfunction from chronic energy deficit or overtraining. Clinical guidelines generally do not require a biopsy-proven structural diagnosis to initiate TRT; instead, they rely on consistent biochemical values plus symptoms after reversible causes are addressed (6, 34).",
        'In contrast, WADA\'s TUE Physician Guidelines for male hypogonadism explicitly state that "TUE should only be granted for organic causes of hypogonadism" and that "functional hypogonadism should not be granted a TUE" (4). WADA\'s concern is that TRT can restore physiological testosterone levels but may also be abused to produce supraphysiological effects, particularly in athletes whose hypogonadism is related to energy deficit, overtraining, or prior anabolic use (4). The organic-only rule therefore seeks to prevent misuse, but it excludes: age-related testosterone decline (LOH), obesity-associated hypogonadism, opioid-induced hypogonadism, and hypothalamic dysfunction from overtraining—all conditions for which clinical guidelines may recommend TRT after conservative measures fail.',
        "The growing masters athlete population is disproportionately affected by this gap. A study of 183 male athletes older than 50 years found that 11.5% had severe testosterone deficiency (<8 nmol/L) and 26.2% had mild deficiency (8–12 nmol/L), with prevalence rising with age (36). The 2024 World Masters Athletics Championships registered 8,029 athletes (22), and the 2027 World Masters Games had more than 24,000 registrants (23). These data indicate that a large and growing population of older competitive athletes may meet clinical criteria for TRT while failing WADA's organic-only TUE criterion. A 52-year-old masters track athlete with documented LOH (testosterone 220 ng/dL on two occasions), persistent symptoms despite six months of lifestyle modification, and an endocrinologist's TRT recommendation faces an irreconcilable conflict between evidence-based medicine and anti-doping compliance (4, 6).",
        "The implications for training and performance are substantial. Untreated or undertreated hypogonadism is associated with decreased lean body mass, increased fat mass, reduced bone mineral density, impaired recovery from training, persistent fatigue, decreased motivation, and depressive symptoms (6). For S&C professionals, these symptoms may manifest as unexplained performance plateaus, difficulty maintaining training loads, prolonged soreness after sessions, and decreased training adherence. The ethical dimension is also noteworthy: denying an athlete access to a treatment considered standard of care in the general population raises questions about the proportionality of anti-doping measures, particularly when the goal of TRT is restoration to normal physiological range rather than supraphysiological enhancement (35).",
    ],
    "Glucocorticoid Administration": [
        "Since 2022, WADA has prohibited all routes of glucocorticoid (GC) administration in-competition, including intra-articular injections that were previously permitted (3, 37). Washout periods were introduced: 3 days for most oral GCs, 10 days for oral triamcinolone, 5 days for intramuscular betamethasone/dexamethasone, and 60 days for intramuscular triamcinolone acetonide (38). Additionally, the 2026 modifications note that sustained-release formulations may produce detectable GC levels beyond published washout periods (3).",
        "In sports medicine practice, intra-articular GC injections are a standard treatment for joint inflammation, tendinopathy, and osteoarthritis flares. The prohibition of these injections in-competition, combined with washout requirements, substantially restricts in-season treatment timing. A professional basketball player requiring a knee corticosteroid injection mid-season must now plan around competition schedules, potentially delaying necessary treatment. For inflammatory bowel disease (IBD) flares requiring oral prednisolone (a standard induction therapy), athletes face additional barriers if the flare coincides with competition periods (37, 38).",
    ],
    "Cardiovascular Disease: Diuretics and Beta-Blockers": [
        "Heart failure management, as outlined in the 2021 ESC Guidelines and subsequent updates, relies on four foundational drug classes: ACE inhibitors/ARNi, beta-blockers, mineralocorticoid receptor antagonists (MRAs such as spironolactone and eplerenone), and SGLT2 inhibitors (8). Of these, MRAs are prohibited under WADA category S5 (diuretics and masking agents), as are loop diuretics (furosemide) essential for congestion management and thiazide diuretics used in hypertension treatment (3, 39).",
        "The blanket prohibition of all diuretics is based on their potential as masking agents. Advanced heart failure generally precludes elite competitive sport, but athletes with earlier-stage or stable heart failure, as well as masters and recreational competitors, may be prescribed MRAs. In such cases, the athlete must either forgo a pillar of standard therapy or navigate the TUE process for spironolactone. Beta-blockers, while not universally prohibited, are banned in-competition in precision sports (shooting, archery, golf, billiards, automotive sports). WADA's rationale for prohibiting beta-blockers in these sports is that they reduce tremor and may steady the hand, effects that could directly improve competitive performance (3). A masters shooting athlete diagnosed with atrial fibrillation faces particular difficulty, as beta-blockers are first-line rate control therapy, yet CAS precedents from 2009 and 2013 have established a high bar for TUE approval in sports where these agents could reduce tremor (3, 8).",
    ],
    "PMOS and Female Fertility Treatment": [
        "In May 2026, an international panel proposed renaming polycystic ovary syndrome (PCOS) to polyendocrine metabolic ovarian syndrome (PMOS) to better reflect its heterogeneous endocrine, metabolic, and reproductive features (40). We have adopted this proposed terminology throughout this review while retaining PCOS in parentheses for reader recognition.",
        "The 2023 International Evidence-Based PCOS Guideline and WHO recommendations position letrozole as the first-line ovulation induction agent for PMOS-related infertility, with clomiphene as second-line (41). Both agents are always prohibited under WADA category S4 (anti-estrogens and aromatase inhibitors) (3). WADA's rationale is that aromatase inhibitors and selective estrogen receptor modulators may be misused to mitigate estrogenic effects of anabolic-androgenic steroid use or to restore endogenous testosterone production (3). Spironolactone, recommended for PMOS-associated hirsutism, is prohibited as a diuretic (S5). Female athletes pursuing fertility treatment must obtain a TUE for time-limited, cycle-specific medication use, requiring disclosure of private reproductive health information to sporting authorities—a privacy concern that may deter athletes from seeking treatment (4, 41).",
    ],
}
CROSS_CUTTING = "Three structural factors underlie the identified gaps (Figure 3). First, a temporal mismatch exists between clinical guideline update cycles and WADA regulatory revisions. Clinical guidelines such as GINA and ADA Standards of Care are updated annually, while WADA TUE Physician Guidelines, though described as living documents, show variable revision frequencies with lags of 1–3 years in some disease areas. Second, a criteria mismatch distinguishes patient-centered clinical decision-making (based on symptoms, biomarkers, and quality of life) from anti-doping criteria emphasizing prevention of performance enhancement. The organic versus functional hypogonadism distinction exemplifies this divergence. Third, an emerging drug class mismatch arises as novel therapeutics (GLP-1 receptor agonists, SGLT2 inhibitors) are incorporated into clinical practice faster than WADA's regulatory framework can evaluate their potential for misuse (3, 5, 33)."
CROSS_CUTTING_2 = "WADA has developed tools to address the misuse of prohibited substances while preserving athlete health, including the Athlete Biological Passport (ABP) for longitudinal monitoring of hematological and steroidal variables and the Anti-Doping Administration and Management System (ADAMS) for TUE submission and sample administration (42, 43). These systems are not anti-athlete; they are designed to protect clean sport. However, accessibility and digital literacy vary across NADOs, and ABP reference ranges may flag physiological restoration achieved through TRT as suspicious, reinforcing the tension between clinical treatment and anti-doping enforcement. The temporal mismatch is particularly well illustrated by comparing update frequencies. GINA has published annual updates every year since 2014, with major revisions in 2019 and 2025. The ADA Standards of Care is updated annually. In contrast, some WADA TUE Physician Guidelines have remained unchanged for 3–4 years despite significant clinical developments in the corresponding disease area. This creates a window during which newly recommended first-line therapies may conflict with TUE guidance that has not yet incorporated the new evidence (3, 4). These structural drivers and their interactions are summarized in the conceptual framework (Figure 4)."
DISCUSSION = [
    "This scoping review represents, to our knowledge, the first systematic mapping of discrepancies between WADA TUE regulations and current clinical practice guidelines across multiple disease domains. Our findings reveal that the clinical-competition gap is not isolated to a single condition but represents a systemic pattern affecting seven major disease areas with varying degrees of severity.",
    "The implications of these gaps extend beyond regulatory inconvenience. Athletes may receive suboptimal medical care when clinicians, aware of anti-doping constraints, prescribe second-line agents to avoid TUE complexity. The TUE process itself, while necessary, imposes time, financial, and privacy burdens that may deter athletes from seeking appropriate treatment—particularly in conditions such as ADHD or PMOS where stigma compounds procedural barriers. Geographic disparities in TUE access further exacerbate these issues, as athletes in resource-limited settings face greater difficulty obtaining specialist evaluations and documentation required for TUE applications (1, 13, 14).",
    "It is important to acknowledge WADA's perspective. WADA's mandate is to protect clean sport by preventing performance enhancement and maintaining a level playing field. Tools such as the Prohibited List, ISTUE, ABP, and ADAMS are designed to apply uniform standards across hundreds of sports and thousands of competitions worldwide (1, 2, 42, 43). Thresholds for inhaled beta-2 agonists and the organic-only rule for testosterone TUEs reflect legitimate concerns about misuse. The challenge is that these protective rules are not always well aligned with the pace of clinical evidence or with the diversity of athlete populations, particularly masters and recreational competitors.",
    'The concept of "no additional performance enhancement beyond restoring normal health" is inherently challenging to operationalize. For testosterone replacement, even physiological-range restoration may influence body composition and recovery. For stimulant medications in ADHD, delineating cognitive normalization from enhancement is conceptually problematic. For beta-2 agonists, the boundary between bronchodilation and potential systemic anabolic effects remains debated, and WADA\'s thresholds are set at doses considered unlikely to confer an unfair advantage (24). These ambiguities create uncertainty for both clinicians and TUE committees, potentially leading to inconsistent decisions across jurisdictions.',
    "The findings of this review align with and extend previous work. Heuberger and Cohen (12) found limited evidence for performance-enhancing effects of many prohibited substances, raising questions about the scientific basis for some prohibitions. Our analysis adds a clinical dimension to this concern by demonstrating that prohibition of specific agents creates measurable gaps in patient care. Data from the International Testing Agency (ITA) TUE dashboard (44) show that TUE application volumes managed by the ITA increased from approximately 650 in 2023 to 850 in 2025, which our disease-specific analysis helps to contextualize—the growing burden reflects both increased awareness and the expanding scope of conditions affected by clinical-competition gaps. The geographic disparities in TUE access reported by Vernec et al. (14) take on additional significance when considered alongside our finding that some disease areas (e.g., ADHD, hypogonadism) require particularly complex and well-documented TUE applications.",
    "From an ethical perspective, the clinical-competition gap raises fundamental questions about the duty of care owed to athletes. The World Medical Association Declaration of Geneva establishes that patient health shall be the physician's first consideration. When anti-doping regulations effectively compel physicians to prescribe second-line treatments, a tension emerges between anti-doping compliance and the ethical obligation to provide optimal care. S&C professionals, while not prescribers, share in this ethical responsibility through their role in monitoring athlete well-being and advocating for appropriate medical care. Addressing the clinical-competition gap therefore requires not only harmonization of TUE criteria with clinical evidence but also standardization of TUE access mechanisms across jurisdictions.",
    "Several limitations of this review should be acknowledged. First, as a scoping review, we mapped the breadth of evidence rather than systematically appraising the quality of individual sources. Second, our gap severity ratings, while based on structured criteria, involve subjective judgment. Third, the review focused on the regulatory text of WADA documents and clinical guidelines; actual TUE approval rates and clinical experiences may differ from what policy documents suggest. Fourth, the rapidly evolving nature of both clinical guidelines and WADA regulations means that specific details may change; the structural analysis and recommendations, however, address persistent systemic issues. Fifth, we acknowledge that WADA has made progress in updating TUE Physician Guidelines, with most disease areas reviewed within the last two years. Our identification of temporal mismatch refers to the structural lag that can occur between updates, not to a lack of any review process.",
]
RECS_INTRO = "We propose the following recommendations for reducing the clinical-competition gap:"
RECS = [
    "Establish a formal mechanism to review and update WADA TUE Physician Guidelines within 12 months of major clinical guideline revisions (e.g., GINA, ADA, Endocrine Society updates).",
    "Re-evaluate the organic/functional distinction for male hypogonadism TUEs in light of the Endocrine Society symptom-plus-biochemistry approach and the growing masters athlete population.",
    "Conduct a formal impact assessment on athletes with type 2 diabetes before adding GLP-1 receptor agonists to the Prohibited List.",
    "Review formoterol dose thresholds in the context of GINA 2025 MART recommendations to ensure athletes can follow guideline-directed asthma therapy without ADRV risk.",
    "Re-evaluate the in-competition-only prohibition of stimulant medications for ADHD, considering the pharmacokinetics of long-acting formulations and the clinical inappropriateness of competition-day discontinuation.",
    "Differentiate diuretic prohibition based on masking potential, considering a streamlined TUE process for MRAs (spironolactone/eplerenone) prescribed for heart failure.",
    "Simplify and digitize TUE applications through ADAMS system improvements, multilingual support, and standardized documentation templates to reduce access disparities.",
    "Integrate anti-doping pharmacology education into medical school curricula, residency training, and continuing medical education to improve prescriber awareness of the Prohibited List.",
]
PRACTICAL_INTRO = "S&C professionals are often the first to notice medication-related performance changes. The following concise actions can help athletes navigate TUE-related treatment decisions (Figure 5):"
PRACTICAL_ITEMS = [
    (
        "Anticipate transitions. ",
        "Adjust training load and recovery when athletes switch medications because of TUE constraints.",
    ),
    (
        "Plan early. ",
        "Encourage athletes to begin TUE applications 21–30 days before competitions and schedule annual renewals during pre-season planning.",
    ),
    (
        "Monitor symptom control. ",
        "Watch for suboptimal control when athletes use second-line agents to avoid TUE complexity, and refer back to the prescribing physician when performance or safety is affected.",
    ),
    (
        "Support guideline-directed therapy. ",
        "Encourage athletes with asthma to use prescribed controller therapy rather than SABA-only treatment, and remind all athletes to check the annually updated WADA Prohibited List before taking new medications.",
    ),
]
DISCLOSURES = [
    ("Declaration of interest", "The authors declare no conflicts of interest."),
    ("Funding", "This work received no external funding."),
    ("Acknowledgments", "None."),
    (
        "Declaration of generative artificial intelligence (AI) in scientific writing",
        "We used generative devin.ai to help with formatting the text and choosing words that suited the tone, and to help writing responses to the reviewers.",
    ),
    (
        "Authors' contribution",
        "O.T.: Conceptualization, Methodology, Software, Formal analysis, Writing - original draft, Writing - review & editing. T.I.: Writing - review & editing.",
    ),
]

FIGURE_LEGENDS = [
    "Figure 1. PRISMA-ScR flow diagram illustrating the source selection process. Database-specific record counts were: PubMed/MEDLINE (n=312), Embase (n=198), SPORTDiscus (n=121), Cochrane Library (n=84), and Web of Science (n=132), for a total of 847 records before deduplication.",
    "Figure 2. Clinical-competition gap risk matrix by disease area and assessment dimension. Severity ratings reflect five dimensions: first-line treatment prohibition, TUE process complexity, guideline update lag, athlete impact, and availability of permitted alternatives.",
    "Figure 3. Timeline of clinical guideline updates and WADA TUE regulatory changes (2018–2026). The timeline illustrates that clinical practice guidelines are updated on annual or near-annual cycles, whereas WADA TUE Physician Guidelines and Prohibited List changes may lag by 1–3 years in some disease areas.",
    "Figure 4. Conceptual framework: structural drivers of the clinical-competition gap. The framework illustrates how evidence-based clinical practice guidelines and WADA anti-doping regulations generate divergent recommendations, producing a clinical-competition gap that affects athlete care. Example: an athlete with adult-diagnosed ADHD and a documented history of symptom control on long-acting methylphenidate would receive first-line therapy under clinical guidelines but must discontinue the medication in-competition unless a TUE is granted, risking cognitive withdrawal during competition.",
    "Figure 5. Clinical-competition gap severity by disease area and assessment dimension. Higher scores indicate greater discrepancy between clinical guideline recommendations and WADA TUE regulations. PMOS=polyendocrine metabolic ovarian syndrome; GLP-1 RA=glucagon-like peptide-1 receptor agonist.",
]
REFS = [
    "1. World Anti-Doping Agency. World Anti-Doping Code International Standard for Therapeutic Use Exemptions (ISTUE). Montreal: WADA; 2021.",
    "2. World Anti-Doping Agency. World Anti-Doping Code 2021. Montreal: WADA; 2021.",
    "3. World Anti-Doping Agency. The 2026 Prohibited List International Standard. Montreal: WADA; 2025.",
    "4. World Anti-Doping Agency. TUE Physician Guidelines – Asthma. Version 9.3. Montreal: WADA; 2026.",
    "5. American Diabetes Association Professional Practice Committee. Standards of Care in Diabetes—2025. Diabetes Care. 2025;48(Suppl 1):S1–S352.",
    "6. Bhasin S, Brito JP, Cunningham GR, et al. Testosterone therapy in men with hypogonadism: an Endocrine Society clinical practice guideline. J Clin Endocrinol Metab. 2018;103(5):1715–1744.",
    "7. Global Initiative for Asthma. Global Strategy for Asthma Management and Prevention. Fontana, WI: GINA; 2025.",
    "8. McDonagh TA, Metra M, Adamo M, et al. 2021 ESC Guidelines for the diagnosis and treatment of acute and chronic heart failure. Eur Heart J. 2021;42(36):3599–3726.",
    "9. National Institute for Health and Care Excellence. Attention deficit hyperactivity disorder: diagnosis and management. NICE guideline [NG87]. London: NICE; 2024 (updated).",
    "10. Allen H, Backhouse SH, Hull JH, Price OJ. Anti-doping policy, therapeutic use exemption and medication use in athletes with asthma: a narrative review. Sports Med. 2019;49(5):659–668.",
    "11. Gerrard D, Pipe A. Therapeutic use exemptions. Med Sport Sci. 2017;62:55–67.",
    "12. Heuberger JAAC, Cohen AF. Review of WADA prohibited substances: limited evidence for performance-enhancing effects. Sports Med. 2019;49(4):525–539.",
    "13. Overbye M, Wagner U. Between medical treatment and performance enhancement: an investigation of how elite athletes experience therapeutic use exemptions. Int J Drug Policy. 2013;24(6):579–588.",
    "14. Vernec A, Healy D, Banon T, Petroczi A. Prevalence of therapeutic use exemptions at the Olympic Games and Paralympic Games: an analysis of data from 2016 to 2022. Br J Sports Med. 2024;58(17):966–972.",
    "15. Tricco AC, Lillie E, Zarin W, et al. PRISMA extension for scoping reviews (PRISMA-ScR): checklist and explanation. Ann Intern Med. 2018;169(7):467–473.",
    "16. Arksey H, O'Malley L. Scoping studies: towards a methodological framework. Int J Soc Res Methodol. 2005;8(1):19–32.",
    "17. Levac D, Colquhoun H, O'Brien KK. Scoping studies: advancing the methodology. Implement Sci. 2010;5:69.",
    "18. Munn Z, Peters MDJ, Stern C, Tufanaru C, McArthur A, Aromataris E. Systematic review or scoping review? Guidance for authors when choosing between a systematic or scoping review approach. BMC Med Res Methodol. 2018;18(1):143.",
    "19. World Anti-Doping Agency. 2023 Anti-Doping Testing Figures Report. Montreal: WADA; 2025.",
    "20. Price OJ, Sewry N, Schwellnus M, et al. Prevalence of lower airway dysfunction in athletes: a systematic review and meta-analysis. Br J Sports Med. 2022;56(4):213–222.",
    "21. Han DH, McDuff D, Thompson D, et al. Attention-deficit/hyperactivity disorder in elite athletes: a narrative review. Br J Sports Med. 2019;53(12):741–747.",
    "22. World Masters Athletics. 2024 WMA Annual Report. 2024.",
    "23. International Masters Games Association. Record registrations: already over 24,000 athletes joining World Masters Games. 2026.",
    "24. Hostrup M, Jacobson GA, Jessen S, Lemminger AK. Anabolic and lipolytic actions of beta2-agonists in humans and antidoping challenges. Drug Test Anal. 2020;12(5):597–609.",
    "25. Australian ADHD Professionals Association. Australian Evidence-Based Clinical Practice Guideline for Attention Deficit Hyperactivity Disorder (ADHD). Melbourne: AADPA; 2022.",
    "26. World Anti-Doping Agency. TUE Physician Guidelines – Attention Deficit Hyperactivity Disorder (ADHD). Version 8.0. Montreal: WADA; 2026.",
    "27. European Medicines Agency. Ozempic: EPAR – summary for the public. 2018 Feb 8.",
    "28. Pharmaceuticals and Medical Devices Agency. Approval of Ozempic subcutaneous injection. 2018 Mar 20.",
    "29. US Food and Drug Administration. FDA approves Ozempic to improve glycemic control in adults with type 2 diabetes. Press release. 2017 Dec 4.",
    "30. European Medicines Agency. Mounjaro: EPAR – summary for the public. 2022 Sep 15.",
    "31. Pharmaceuticals and Medical Devices Agency. Approval of Mounjaro subcutaneous injection. 2023 Apr.",
    "32. US Food and Drug Administration. FDA approves Mounjaro (tirzepatide) injection for type 2 diabetes. Press release. 2022 May 13.",
    "33. World Anti-Doping Agency. 2026 Monitoring Program. Montreal: WADA; 2025.",
    "34. European Association of Urology. EAU Guidelines on Sexual and Reproductive Health. Arnhem: EAU; 2024.",
    "35. Lincoff AM, Bhasin S, Flevaris P, et al. Cardiovascular safety of testosterone-replacement therapy. N Engl J Med. 2023;389(2):107–117.",
    "36. Di Luigi L, Sansone P, Sgrò P, et al. Prevalence of undiagnosed testosterone deficiency in aging athletes: does exercise training influence the symptoms of male hypogonadism? J Sex Med. 2010;7(4 Pt 1):1361–1369.",
    "37. World Anti-Doping Agency. Glucocorticoids and Therapeutic Use Exemptions Guidelines. Montreal: WADA; 2025.",
    "38. World Anti-Doping Agency. Glucocorticoids washout table—2026. Montreal: WADA; 2025.",
    "39. Mancia G, Kreutz R, Brunstrom M, et al. 2023 ESH Guidelines for the management of arterial hypertension. J Hypertens. 2023;41(12):1874–2071.",
    "40. Teede HJ, Azziz R, Balen AH, et al. Polyendocrine metabolic ovarian syndrome: a proposal for the renaming of polycystic ovary syndrome. Lancet. 2026; published online May 13, 2026.",
    "41. Teede HJ, Tay CT, Laven JJE, et al. Recommendations from the 2023 international evidence-based guideline for the assessment and management of polycystic ovary syndrome. J Clin Endocrinol Metab. 2023;108(10):2447–2469.",
    "42. World Anti-Doping Agency. Athlete Biological Passport Operating Guidelines. Version 9.0. Montreal: WADA; 2023.",
    "43. World Anti-Doping Agency. Anti-Doping Administration and Management System (ADAMS). Montreal: WADA; 2024.",
    "44. International Testing Agency. Behind the numbers: ITA publishes TUE dashboard to strengthen transparency in the global fight against doping in sport. 2026 Mar 17. Available at: https://ita.sport/news/behind-the-numbers-ita-publishes-tue-dashboard-to-strengthen-transparency-in-the-global-fight-against-doping-in-sport/",
]
print("SCJ English content data loaded.")
